services:
  astro-app:
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run dev
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 3000:3000
    networks:
      - app-network

  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - 80:80
      - 443:443
    depends_on:
      - astro-app
    links:
      - astro-app
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /etc/nginx/vhost.d
      - /usr/share/nginx/html
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy
    networks:
      - app-network

  #Nginx Service
  nginx:
    image: nginx:alpine
    mem_limit: 2048m
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
    expose:
      - "80"
      - "443"
    depends_on:
      - astro-app
      - nginx-proxy
    links:
      - astro-app
    environment:
      - VIRTUAL_HOST=astro-app.local
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=astro-app.local
      - LETSENCRYPT_EMAIL=manu12.jmrr@gmail.com
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
